spring.application.name=market-service
server.port=7073
spring.datasource.url=jdbc:postgresql://localhost:5432/broker_market
spring.datasource.username=postgres
spring.datasource.password=mypassword
finnhub.api.key = apikey
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
logging.level.org.hibernate=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
