spring.application.name=auth-service
server.port=7071
spring.datasource.url=jdbc:postgresql://localhost:5432/broker_auth
spring.datasource.username=postgres
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
logging.level.org.hibernate=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG