spring.application.name=gateway-service
server.port=7070
spring.datasource.url=jdbc:postgresql://localhost:5432/broker_auth
spring.datasource.username=postgres
spring.datasource.password=mypassword
spring.security.oauth2.resourceserver.jwt.secret-key=ZzYJ/6d54kjZQM2z0a02xMfHyZAeDq+krlmL8DAnR5KiyeLQfEvj19ZgkLmXX7WcZd3L5XsCNN04B+X0jhhKbg==
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
logging.level.org.hibernate=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
